# Generated by Django 4.2 on 2024-10-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='lifestyle_score',
        ),
        migrations.AddField(
            model_name='userdata',
            name='diet_quality',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='userdata',
            name='exercise_frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='medical_history',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='smoking_status',
            field=models.CharField(default='non-smoker', max_length=10),
        ),
        migrations.AddField(
            model_name='userdata',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='diabetes_risk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(default='Not specified', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='insurance_risk',
            field=models.IntegerField(default=0),
        ),
    ]
